name: Smoke Test CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Execute full install
      shell: bash
      run: |
        set -o pipefail
        sh mac 2>&1 | tee ~/laptop.log

